name: publish

on:
  push:
    branches: [ paipo ]
    paths: [ xmr-stack-rx/Docker/** ]

  workflow_dispatch:

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the xmr Docker image
        run: |
          echo $PAT | docker login ghcr.io -u paoliveira --password-stdin
          docker build xmr-stack-rx/Docker/. --tag ghcr.io/paoliveira/xmr:4core
          docker run ghcr.io/paoliveira/xmr:4core
          docker push ghcr.io/paoliveira/xmr:4core
        env:
          PAT: ${{ secrets.PAT }}
